# Generated by Django 5.2.7 on 2026-02-02 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="category/icons/"),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="subcategory/icons/"
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcategories",
                to="catalog.category",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together={("parent_category", "name")},
        ),
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
        migrations.AlterModelTable(
            name="subcategory",
            table="sub_categories",
        ),
    ]
