# Generated by Django 5.2.7 on 2026-02-24 15:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_options_alter_subcategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.ImageField(upload_to="Brand/icons/")),
            ],
            options={
                "db_table": "Brand",
                "ordering": ["name"],
            },
        ),
    ]
