# Generated by Django 5.2.7 on 2025-10-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(default="Dhaka", max_length=255),
        ),
    ]
