# Generated by Django 5.2.7 on 2025-10-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_email_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
