# Generated by Django 5.2.7 on 2025-10-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="rahat@gmail.com", max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
