# Generated by Django 5.2.7 on 2026-02-24 15:45

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.profile_image_upload_to
            ),
        ),
    ]
